routes/web.php
<?php

use App\Http\Controllers\GuestController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\StarController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {

	Route::prefix('admin')->group(function () {
		// Profile
	    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
	    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
	    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

	    // Ressources
	    Route::resource('stars', StarController::class);
	});
});

Route::get('/stars', [GuestController::class, 'stars'])->name('stars');


require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/ressources/stars-create-update.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Stars') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
			@if ($errors->any())
				<div class="p-5 mb-10 bg-rose-200 border border-rose-300 sm:rounded-lg">
					<strong>Whoops!</strong> There were some problems with your input.<br><br>
					<ul>
						@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif

			@if ($message = Session::get('success'))
        		<div class="p-5 mb-10 bg-emerald-200 border border-emerald-300 sm:rounded-lg">
					<p>{{ $message }}</p>
				</div>
			@endif

            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
				<div class="p-6 text-gray-900">
					<div>
						<div class="md:grid md:grid-cols-3 md:gap-6">
							<div class="md:col-span-1">
								<div class="px-4 sm:px-0">
									<h3 class="mb-4 text-lg font-medium leading-6 text-gray-900">
										@if(isset($star))
											Édition du profil de star de {{ $star->firstname }} {{ $star->lastname }}
										@else
											Création du profil d'une star
										@endif
									</h3>
								</div>
							</div>
						</div>
						<div class="mt-10 md:col-span-2 md:mt-0">
							@if(isset($star))

								<form method="POST" enctype="multipart/form-data" action="{{ route('stars.update', $star->id) }}">
						            @method('PUT')
							@else
								<form method="POST" enctype="multipart/form-data" action="{{ route('stars.store') }}">
							@endif
						    @csrf
          						<div class="space-y-6 bg-white py-5 sm:p-6">
									<div>
										<label for="lastname" class="block text-sm font-medium text-gray-700">Nom de famille<sup>*</sup> :</label>
										<div class="relative mt-1 rounded-md shadow-sm">
											<input type="text" name="lastname" id="lastname" class="block w-full rounded-md border-gray-300 pl-7 pr-12 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" placeholder="" value="@if(isset($star)){{ $star->lastname }}@endif">
										</div>
									</div>

									<div>
										<label for="firstname" class="block text-sm font-medium text-gray-700">Prénom<sup>*</sup> :</label>
										<div class="relative mt-1 rounded-md shadow-sm">
											<input type="text" name="firstname" id="firstname" class="block w-full rounded-md border-gray-300 pl-7 pr-12 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" placeholder="" value="@if(isset($star)){{ $star->firstname }}@endif">
										</div>
									</div>

									<div>
										<label class="block text-sm font-medium text-gray-700">Image</label>
										<div class="mt-1 flex items-center">
											@if(!isset($star) || (isset($star) && empty($star->image_path)))
												<span class="inline-block h-12 w-12 overflow-hidden rounded-full bg-gray-100">
													<svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
														<path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
													</svg>
												</span>
											@else
												<img class="max-w-xs" src="{{ asset('images/'. $star->image_path) }}" />
											@endif
											<input type="file" class="ml-5 rounded-md border border-gray-300 bg-white py-2 px-3 text-sm font-medium leading-4 text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" name="image" />
										</div>
									</div>

									<div>
										<label for="description" class="block text-sm font-medium text-gray-700">{{ __('Description') }}</label>
										<div class="mt-1">
											<textarea id="description" name="description" rows="8" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" placeholder="">@if(isset($star)){{ $star->description }}@endif</textarea>
										</div>
									</div>
								</div>
								<div class="pt-4">
									<button type="submit" class="inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">Enregistrer</button>
								</div>

							</form>
						</div>
					</div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/ressources/stars-index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Stars') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
			@if ($errors->any())
				<div class="p-5 mb-10 bg-rose-200 border border-rose-300 sm:rounded-lg">
					<strong>Whoops!</strong> There were some problems with your input.<br><br>
					<ul>
						@foreach ($errors->all() as $error)
							<li>{{ $error }}</li>
						@endforeach
					</ul>
				</div>
			@endif

			@if ($message = Session::get('success'))
        		<div class="p-5 mb-10 bg-emerald-200 border border-emerald-300 sm:rounded-lg">
					<p>{{ $message }}</p>
				</div>
			@endif
			
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
        		<div class="p-6 flex justify-between">
        			<h3 class="text-xl">Liste des stars</h3>
					<a href="{{ route('stars.create') }}" class="button inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" title="Ajouter une star">Ajouter une star</a>
        		</div>
                <div class="p-6 text-gray-900">
                	<table class="w-full text-sm text-gray-500 dark:text-gray-400 table-fixed">
                		<thead class="text-xs text-gray-700 uppercase bg-gray-50">
                			<tr class="border-b">
                				<th class="p-2 text-left">{{ __('Nom') }}</th>
                				<th class="p-2 text-left">{{ __('Prénom') }}</th>
                				<th class="p-2 text-center ">{{ __('Actions') }}</th>
                			</tr>
                		</thead>
                		<tbody>
                			@if(isset($stars) && count($stars) > 0)
                				@foreach($stars as $star)
                					<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                						<td class="p-2 text-left">{{ $star->lastname }}</td>
                						<td class="p-2 text-left">{{ $star->firstname }}</td>
                						<td class="p-2 text-center">
                							<a href="{{ route('stars.show', $star->id) }}" class="inline-flex items-center px-2 py-1 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150 ml-3" title="Voir la star">Voir</a>
                							<a href="{{ route('stars.edit', $star->id) }}" class="inline-flex items-center px-2 py-1 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150 ml-3" title="Modifier la star">Modifier</a>
											<form action="{{ route('stars.destroy', $star->id) }}" method="POST" style="display: inline;">
												@csrf
												@method('DELETE')
												<button type="submit" class="inline-flex items-center px-2 py-1 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:ring ring-gray-300 disabled:opacity-25 transition ease-in-out duration-150 ml-3">Supprimer</button>
											</form>
                						</td>
                					</tr>
                				@endforeach
            				@else
            					<tr><td cospla="3">Aucune star en base de données</td></tr>
        					@endif
        				</tbody>
        			</table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/ressources/stars-show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Stars') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if ($errors->any())
                <div class="p-5 mb-10 bg-rose-200 border border-rose-300 sm:rounded-lg">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @if ($message = Session::get('success'))
                <div class="p-5 mb-10 bg-emerald-200 border border-emerald-300 sm:rounded-lg">
                    <p>{{ $message }}</p>
                </div>
            @endif
            
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6">
                    <h3 class="text-xl">{{ $star->firstname }} {{ $star->lastname }}</h3>
                </div>
                @if($star->image_path)
                    <div class="px-6 pb-6">
                        <img class="max-w-xs" src="{{ asset('images/'. $star->image_path) }}" />
                    </div>
                @endif
                <div class="px-6 text-gray-900">
                    {!! nl2br($star->description) !!}
                </div>
                <div class="p-6">
                    <a href="{{ route('stars.index') }}" class="button inline-flex justify-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" title="Retourner à la liste des stars">Retour à la liste</a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>